import Foundation
import Testing

@Suite
struct SwiftHTMLGeneratedCSSPropertiesTests {
    @Test
    func generatedStylePropertiesHaveStableSourceAndShape() throws {
        let source = try repositoryRoot().appending(
            path: "Sources/SwiftHTML/Elements/StyleProperties.generated.swift"
        )
        let content = try String(contentsOf: source, encoding: .utf8)
        let records = generatedStylePropertyRecords(in: content)

        #expect(content.contains("Generated by scripts/generate-swift-html-css-properties.mjs"))
        #expect(content.contains("@mdn/browser-compat-data 8.0.3 css.properties"))
        #expect(records.count == 564)
        #expect(records.map(\.property) == records.map(\.property).sorted())
        #expect(Set(records.map(\.property)).count == records.count)
        #expect(Set(records.map(\.helper)).count == records.count)
        #expect(!records.contains { $0.property.hasPrefix("-") })
        #expect(records.contains(GeneratedStylePropertyRecord(helper: "zIndex", property: "z-index")))
        #expect(records.contains(GeneratedStylePropertyRecord(helper: "animationTimeline", property: "animation-timeline")))
    }

    @Test
    func generatedStylePropertyDriftCheckScriptExists() throws {
        let script = try repositoryRoot().appending(
            path: "scripts/generate-swift-html-css-properties.mjs"
        )
        let content = try String(contentsOf: script, encoding: .utf8)

        #expect(content.contains("--check"))
        #expect(content.contains("standard_track === true"))
        #expect(content.contains("status.deprecated !== true"))
        #expect(content.contains("name.startsWith(\"-\")"))
    }
}

private struct GeneratedStylePropertyRecord: Equatable, Hashable {
    let helper: String
    let property: String
}

private func repositoryRoot() throws -> URL {
    URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
}

private func generatedStylePropertyRecords(in content: String) -> [GeneratedStylePropertyRecord] {
    content.split(separator: "\n").compactMap { line in
        let text = String(line)
        guard
            let helperStart = text.range(of: "static func ")?.upperBound,
            let helperEnd = text.range(of: "(_ value: String)")?.lowerBound,
            let propertyStart = text.range(of: "Style.property(\"")?.upperBound,
            let propertyEnd = text[propertyStart...].range(of: "\", value)")?.lowerBound
        else {
            return nil
        }

        return GeneratedStylePropertyRecord(
            helper: String(text[helperStart..<helperEnd]).trimmingCharacters(in: CharacterSet(charactersIn: "`")),
            property: String(text[propertyStart..<propertyEnd])
        )
    }
}
